### ISSUE TITLE
Colaboradores e sincronização

### ISSUE THREAD

**Issue by hgees** [hgees/wumpusgrp2#1]
Adicionar colaboradores e sincronizar repositório

**Comment by hgees** [comment]
Favor, confirmar aqui que foi adicionado.
Grato.

**Comment by pontesupe** [comment]
Confirmado.

**Comment by JorgeEd13** [comment]
Precisava mesmo confirmar?…confirmado também
Em 17/11/2015 7:42 PM, "Matheus Pontes Agostinho" notifications@github.com
escreveu:

**Comment by guidoferrario** [comment]
Confirmado.

**Comment by hgees** [comment]
Todos confirmados... Issue fechada
