### ISSUE TITLE
Conferir milestones

### ISSUE THREAD

**Issue by drbeco** [hgees/wumpusgrp2#11]
| N | Data | Milestone | Descrição |
| --- | --- | --- | --- |
| 1 | 17/11/15 | Versão 0.1 | Criar repositório, rascunhos, clones, ramos, add autores |
| 2 | 19/11/15 | Versão 0.2 | Fazer um agente funcional mínimo que passeie pelo labirinto |
| 3 | 26/11/15 | Versão 0.3 | Colocar alguma inteligência no agente |
| 4 | 03/12/15 | Versão 0.4 | Melhorar as respostas dadas para as percepções do agente |
| 5 | 10/12/15 | Versão 0.5 | Lembrar dos caminhos, casas seguras, pegar o ouro com sucesso |
| 6 | 17/12/15 | Versão 1.0 | Buscar a saída através de caminho seguro. Versão Final |
| 7 | 20/12/15 | Versão 1.1 | Versão final após adiamento. |

**Comment by guidoferrario** [comment]
Milestones conferidas e corrigidas!

**Comment by drbeco** [comment]
Não deveria ter fechado sem corrigir todos problemas.

Falta criar milestones. Confira toda tabela.

**Comment by guidoferrario** [comment]
Perdão pelo erro, professor. Milestone adicionado.
