### ISSUE TITLE
frente(Pos0, Angulo, Pos1)

### ISSUE THREAD

**Issue by drbeco** [hgees/wumpusgrp2#13]
Pessoal, a "sugestão" é compulsória:

Faça um predicado que calcule a posição P1, que é a posição imediatamente na "frente" da posição P0, dados P0 e ângulo.

Por exemplo, seja `P0=[2,1]` onde `Coluna=2` e `Linha=1`:

```
?- frente([2,1], 0, X).        % para direita
X = [3,1]                      %
?- frente([2,1], 90, X).       % para cima
X = [2,2]                      %
?- frente([2,1], 270, X).      % para baixo
X = [2,1]                      % trombou, fica na mesma
?-
```

**Comment by hgees** [comment]
Função feita. Issue fechada
