### ISSUE TITLE
Failed miserably

### ISSUE THREAD

**Issue by drbeco** [hgees/wumpusgrp2#15]
## Atualização (master/develop)

A mensagem 
`External function run_agent(Percept, No Action) failed miserably!`
agora mostra qual foi a percepção que o agente recebeu que não soube retornar uma ação.

**Comment by hgees** [comment]
Obrigado pela informação professor, o ultimo que confirmar a leitura fecha a issue

**Comment by guidoferrario** [comment]
Confirmando a leitura, e mais uma vez enaltecendo o auxílio dado pela mensagem. :+1:

**Comment by pontesupe** [comment]
Ok, compreendi a mensagem.
Obrigado.
