### ISSUE TITLE
Apenas um :- dynamic

### ISSUE THREAD

**Issue by drbeco** [hgees/wumpusgrp2#17]
O predicado `dynamic` aceita como parâmetro uma lista de predicados. Então não é para criar um dynamic para cada fato dinâmico, e sim coloca-los todos na lista.

**Comment by hgees** [comment]
Ok professor, erro reparado.
Deixarei a issue aberta para que outros possam também aprender.

**Comment by drbeco** [comment]
`dynamic/1` = aceita **um** argumento, que é **uma** lista, e não duas listas.

**Comment by drbeco** [comment]
Estou olhando a versão atual do develop e não está corrigido.

**Comment by drbeco** [comment]
Continua errado (ramo develop, 2015-12-05, 13h05)

![image](https://cloud.githubusercontent.com/assets/5805111/11608750/ed8e2e96-9b50-11e5-9004-52cb170eb473.png)

**Comment by drbeco** [comment]
Quando resolver, feche o bug com uma mensagem "corrigido"

**Comment by pontesupe** [comment]
Corrigido.
