### ISSUE TITLE
Casa Atual

### ISSUE THREAD

**Issue by hgees** [hgees/wumpusgrp2#18]
Pessoal, acabei de criar a parte da percepção de casas adjacentes pensando que ele já atualizava a casa atual mas como isso não ocorre eu não pude testar se o codigo esta funcionando. gostaria de ideias para fazer tal parte do codigo. Obrigado.

**Comment by drbeco** [comment]
Dica: a casa atual é um fato dinâmico que é inicializado (`assert`) com o valor `[1,1]` e vai ser alterado somente quando ocorrer uma ação `goforward`. (A ação de girar para esquerda ou direita não altera a casa atual).

**Comment by guidoferrario** [comment]
Ao executar o agente percebi que o mesmo problema ocorre com a informação da casa atual. Acredito que a solução para os dois problemas seja de maneira bastante próxima.

**Comment by guidoferrario** [comment]
Problema resolvido.
