### ISSUE TITLE
Bug do loop infinito

### ISSUE THREAD

**Issue by JorgeEd13** [hgees/wumpusgrp2#22]
A função:

```
coragem([_,yes,_,_,_], turnleft) :- 
    mudadiresq.
```

está causando um bug no comportamento do agente ao sentir uma brisa, ele muda de direção mas não sai da casa, então ele sente a mesma brisa e continua girando sem sair até que o programa termine.
Tentativas de soluções já utilizadas:

```
assert(ventando([turnleft, turnleft, goforward, turnright, goforward, turnright])),

coragem([_,yes,_,_,_], A):-
     ventando([A|S]),
     retractall(ventando(_)),
     assert(ventando(S)).
```

&

```
coragem([_,yes,_,_,_], [turnleft, turnleft, goforward, turnright, goforward, turnright]):-
     mudadiresq.
```

Ambas as tentativas resultaram em Failed miserably.

**Comment by JorgeEd13** [comment]
Detalhe a acrescentar, por algum motivo os sinais de barra "_" sumiram quase todos do comentário no geral, mesmo eu tentando editar, espero que isso não cause confusão.

**Comment by drbeco** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by hgees** [comment]
Está sendo trabalhado num tipo novo de movimentação onde o agente anda pela periculosidade da casa da frente.
Creio que dessa maneira tal bug irá sumir.

**Comment by drbeco** [comment]
Pode explicar melhor como será essa nova movimentação?

**Comment by guidoferrario** [comment]
O agente deve analisar a casa da frente,se esta for segura ele deverá retornar a ação goforward; senão deve retornar a ação turnleft, e então analisar mais uma vez se a casa a frente é segura.

**Comment by guidoferrario** [comment]
Problema resolvido.
