### ISSUE TITLE
Colaboradores

### ISSUE THREAD

**Issue by drbeco** [hgees/wumpusgrp2#5]
Todos colaboradores, postar mensagem que estão adicionados.

O último, fechar o bug.

**Comment by hgees** [comment]
Confirmação de todos já feita em outra issue
https://github.com/hgees/wumpusgrp2/issues/1

Mesmo assim, 
Estou adicionado e ativo

**Comment by guidoferrario** [comment]
Confirmação feita em outra issue. De qualquer maneira, confirmando mais uma vez.

**Comment by JorgeEd13** [comment]
Confirmando
Em 21/11/2015 4:16 PM, "Guido De Lyra Ferrario" notifications@github.com
escreveu:

**Comment by drbeco** [comment]
Ok, se tudo já está certo (outra issue) pode fechar.
