### ISSUE TITLE
Simulador V.3

### ISSUE THREAD

**Issue by drbeco** [hgees/wumpusgrp2#6]
Cientes que mudou a versão do simulador?

Agora só sorteia 3 buracos!

Use:

`wumpusworld(pit3, 4).`

**Comment by hgees** [comment]
Completamente ciente professor,
Assim que possível faremos a alteração e retornaremos

**Comment by pontesupe** [comment]
Sim professor,
A versão já foi atualizada.

**Comment by drbeco** [comment]
*\* ATENÇÃO **

Nova atualização. Coloquei uma definição de módulo, para proteger o simulador de acesso indevido do agente.

A única função externa do simulador é a função `start`, para começar o jogo.

O resto é interna e não deve ser usada. Qualquer dedução sobre o mundo o agente deve fazer por si só, por seus próprios meios (e não consultar o simulador).

Atualizem os seus ramos master e develop (`git pull`).

---

Após lerem aqui, o último fechar o bug.

**Comment by hgees** [comment]
Favor confirmar aqui que leram, o ultimo fecha o bug

**Comment by guidoferrario** [comment]
Confirmado! :+1:

**Comment by pontesupe** [comment]
Confirmado.
