### ISSUE TITLE
Erro na movimentação

### ISSUE THREAD

**Issue by hgees** [hgees/wumpusgrp2#7]
Meus caros,

Após a implementação do novo mapa (wumpus3.pl) o agente está com um problema que não tinha antes. O fato que o fazia parar ao sentir uma brisa ou um fedor não funciona mais e o agente continua executando o gofoward.
Gostaria da ajuda de todos para resolver este problema.

**Comment by drbeco** [comment]
Vou conferir se é problema no wumpus3.pl ou no código de vocês. Seria importante se pudesse relatar o problema com mais detalhes.

**Comment by hgees** [comment]
Agradeço a atenção, já enviei um link ao seu email com o texto do erro.

**Comment by drbeco** [comment]
ATUALIZAÇÃO: Já detectei o erro. Como diriam os amantes ao terminar o namoro: _"o problema sou eu, não é você."_
Devo corrigir até o fim da noite e fazer novo push no develop e no merge de todos grupos. Este tempo será descontado da data de entrega.

**Comment by drbeco** [comment]
E não é que no final das contas acabou que _"o problema é você, não sou eu"_. :trollface:

**Comment by drbeco** [comment]
Desculpe minha "pressa" de fechar. Não é meu trabalho. Vou abrir novamente só para dar a chance de alguém "capitalizar" a ação de fechar. Só fechar e tá ok. Já resolvido.

**Comment by hgees** [comment]
Bug resolvido,
Issue fechada.
