### ISSUE TITLE
Predicados do simulador

### ISSUE THREAD

**Issue by drbeco** [hgees/wumpusgrp2#8]
Caros,

Não se pode usar NENHUM predicado do simulador, EXCETO esses 4:

```
wumpusworld(pit3, 4)
init_agent
restart_agent
run_agent(Percepcao, Acao)
```

Reparei que vocês estão usando `agent_arrows/1` em parte do código.

Se quiser saber quantas flechas tem, inicialize um predicado de sua própria criação com valor "1" (para isso que serve `init_agent`) e diminua ele para zero quando atirar.

Ao corrigir este bug (apagar o predicado), feche aqui o issue.

**Comment by hgees** [comment]
predicado apagado
